### ISSUE TITLE
Adding UserEventHandler causes no items to be added to cart

### ISSUE THREAD

**Issue by nWidart** [cartalyst/demo-cart#6]
Hello,

I'm currently having an issue with the [`UserEventHandler`](https://github.com/cartalyst/demo-cart/blob/master/app/handlers/UserEventHandler.php), on a laravel 5.1 application.
Everything up until the point to added this class is working fine. Ie: added / removing / updating items to the cart.

Now I would like to sync these carts to the database, when a user logs in.

When adding the `UserEventHandler` class to the `$subscribe` property, no more items are added to the carts.

I don't why this is, as the method `onUserAuthenticated` is not called when already logged in / or when not yet logged in. Yet it prevents items to be added to the cart.

Did I miss something ? 

Thank you

**Comment by nWidart** [comment]
I managed to work around this issue by triggering an event myself when a user logs in. And when this happens triggering an event handle that syncs the carts with each other.

**Comment by brunogaspar** [comment]
The demo is on 4.2 so you most likely need to adjust the event handler to work properly on Laravel 5.1 and above.

**Comment by nWidart** [comment]
The event handler was working, since it was triggered on authentication. But somehow it prevented items to be added to the cart.

**Comment by brunogaspar** [comment]
You can't add new items to the cart if the event handler is setup?

I'm quite confused on the issue you're having.

**Comment by nWidart** [comment]
> When adding the UserEventHandler class to the $subscribe property, no more items are added to the carts.

Which indeed means no more items are added to the cart once it's setup.

It works with the workaround, but just found it curious as to why it was behaving this way.

**Comment by brunogaspar** [comment]
I managed to reproduce this while i was updating the demo to Laravel 5.1.

I've fixed it by changing the namespace of the cart import on the user event handler to `Cartalyst\Cart\Laravel\Facades\Cart;`.

With this it started to work as expected.
