### ISSUE TITLE
composer install fatal error - cartalyst/conditions not found

### ISSUE THREAD

**Issue by sjzurek** [cartalyst/demo-cart#8]
```
$ composer install 
[...]
fatal: repository 'https://***:***@github.com/cartalyst/conditions.git/' not found  
```

**Comment by brunogaspar** [comment]
Hello @sjzurek 

To fully install this demo you'll need to have a paid Cartalyst Subscription which is mentioned [here](https://github.com/cartalyst/demo-cart#installation).

Hope it helps.

Regards
